
services:
  mazegame:
    build: 
      context: .
      dockerfile: x11-Dockerfile
      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTH:$XAUTH
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    network_mode: "host"

    
